apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-migration-connection
  namespace: stakeholder-api
spec:
  encryptedData:
    db: AgAe1JnDsXyREq8pDFZCDjrueWJPfZ+Xj3QfYswMR896eUDZcFWHkNB3GgfZW5Djh8h74SnJJ59oFQs920DEI7yhK1iltfvdotUglz/y0FjMhqo9oTmBWunQaLwz5uaQ8pHHEdpv36WtHJGRZeHEq2AB9ZmZLCIMXwxTMhsTW6PWFP+WOjzCaKxRB/SZnltQOa2IAFdLficKv20l6LGrKflujfRryIjIdeDFWmorAZ/YoCTm4EkH4SlHkddW6odLLzOqEwyBnNgcH/oTH8CXQ/u4nDQ89QVsZ/WmVtMFag5+88swJrN/gb80T06gxFjQxFqhU5f/m7KnJbRUPk0HwNHBBzb/TZ648Gau8Sb3TBYEW33zadCWkIxygqUs3Xvv9G8tGGWUVFxrEEAcyL4tdh4nH9iME9jtRU79CASQISCjuK7sOq2eKOm93dyo7IgpfMTxM9UuHChmYnKyaw5If6pZb3qWaUa5/Y6/sKPXlfFK6nrmjgWLwd8tcudNl8wCbLFg7LKU1nBA3M6MakeICZU2hOPDAVmhmdMqpFdyf86jVYNRMlnEv+/7wu+r7fOV1lnu/GAbPtcbsI8+tQGA4zZzk1L2v/Mwvisn3pv59QBGHNlAWXe+/HyXiZKCvtdTOZBp7HLcFYeafrfoJmHR755gGjjg3+BtDlGJQccS0sVDJLvN33q6/oCbventcmi0srqiUG14ojYF+nhEsf+/Jd18o0FuvM6J74LkLj/SQJSFeG0weoCgCoXxNYVBsTaG9Mz6hcCJNvez4BLIJ6duoPMhqTe7pHHHSjempTdaribOO1kSN9GCyIMrIIkRQK+h17d+0/IyrtjHnTVLgZXlihlECS7vv6IQ/U4yUpFfY7iCBBrIDaUcSEoIbvC3PTkMiT72mGfyRVATgj0AjX4=
  template:
    metadata:
      creationTimestamp: null
      name: database-migration-connection
      namespace: stakeholder-api

