exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('stakeholder')
    .del()
    .then(function () {
      // Inserts seed entries
      return knex('stakeholder').insert([
        {
          id: '792a4eee-8e18-4750-a56f-91bdec383aa6',
          type: 'Organization',
          org_name: 'Greenstand',
          first_name: '',
          last_name: '',
          email: 'hello@greenstand.com',
          phone: '123-123-2122',
          pwd_reset_required: null,
          password: null,
          wallet: null,
          salt: null,
          offering_pay_to_plant: null,
          active_contract_id: null,
          tree_validation_contract_id: null,
          website: 'greenstand',
          logo_url: './logo_192x192.png',
          map: '/greenstandMap',
          organization_id: 1,
          owner_id: null,
        },
        {
          id: 'a8567323-88b1-4870-8c48-68d2da3ab356',
          type: 'Organization',
          org_name: 'Greenstance',
          first_name: '',
          last_name: '',
          email: 'hello@greenstance.com',
          phone: '123-123-1234',
          pwd_reset_required: null,
          password: null,
          wallet: null,
          salt: null,
          offering_pay_to_plant: null,
          active_contract_id: null,
          tree_validation_contract_id: null,
          website: 'greenstance.com',
          logo_url: './logo_192x192.png',
          map: '/greenstance',
          organization_id: null,
          owner_id: null,
        },
        {
          id: 'c92189d2-2d55-44bc-a0b4-0dad25dc9f35',
          type: 'Organization',
          org_name: 'Green Space',
          first_name: '',
          last_name: '',
          email: 'greenspace@green.com',
          phone: '123-123-1324',
          pwd_reset_required: null,
          password: null,
          wallet: null,
          salt: null,
          offering_pay_to_plant: null,
          active_contract_id: null,
          tree_validation_contract_id: null,
          website: 'greenspace.com',
          logo_url: './logo_192x192.png',
          map: '/greenspace',
          organization_id: null,
          owner_id: null,
        },
        {
          id: '344a6130-9094-4a05-8fd6-faf176593fbc',
          type: 'Organization',
          org_name: 'Green World',
          first_name: '',
          last_name: '',
          email: 'hi@greenworld.com',
          phone: '123-123-1234',
          pwd_reset_required: null,
          password: null,
          wallet: null,
          salt: null,
          offering_pay_to_plant: null,
          active_contract_id: null,
          tree_validation_contract_id: null,
          website: 'greenworld.com',
          logo_url: './logo_192x192.png',
          map: '/greenworld',
          organization_id: null,
          owner_id: null,
        },
        {
          id: '1a05ec87-3c38-4395-b9f3-aa15becedc31',
          type: 'Organization',
          org_name: 'Child One',
          first_name: '',
          last_name: '',
          email: 'child@gmail.com',
          phone: '123-123-1234',
          pwd_reset_required: null,
          password: null,
          wallet: null,
          salt: null,
          offering_pay_to_plant: null,
          active_contract_id: null,
          tree_validation_contract_id: null,
          website: 'childone.com',
          logo_url: './logo_192x192.png',
          map: '/childOne',
          organization_id: null,
          owner_id: null,
        },
        {
          id: '1d2fb06e-e8f7-40de-8e13-ed3eba1abb3a',
          type: 'Organization',
          org_name: 'Child Two',
          first_name: '',
          last_name: '',
          email: 'childtwo@gmail.com',
          phone: '123-234-1234',
          pwd_reset_required: null,
          password: null,
          wallet: null,
          salt: null,
          offering_pay_to_plant: null,
          active_contract_id: null,
          tree_validation_contract_id: null,
          website: 'childtwo.com',
          logo_url: './logo_192x192.png',
          map: '/childTwo',
          organization_id: null,
          owner_id: null,
        },
        {
          id: '35a23de8-f1ab-4409-be79-3c6a158d5bde',
          type: 'Person',
          org_name: '',
          first_name: 'Grower',
          last_name: 'One',
          email: 'growerOne@gmail.com',
          phone: '123-123-1234',
          pwd_reset_required: null,
          password: null,
          wallet: null,
          salt: null,
          offering_pay_to_plant: null,
          active_contract_id: null,
          tree_validation_contract_id: null,
          website: '',
          logo_url: './person_192x192.png',
          map: '/childtwo',
          organization_id: null,
          owner_id: null,
        },
        {
          id: '90eef52b-ad55-4953-ace9-6a324ae6cec2',
          type: 'Person',
          org_name: '',
          first_name: 'Grower',
          last_name: 'Two',
          email: 'growerTwo@gmail.com',
          phone: '123-123-1235',
          pwd_reset_required: null,
          password: null,
          wallet: null,
          salt: null,
          offering_pay_to_plant: null,
          active_contract_id: null,
          tree_validation_contract_id: null,
          website: '',
          logo_url: './person_192x192.png',
          map: '',
          organization_id: null,
          owner_id: null,
        },
      ]);
    });
};
