apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-migration-connection
  namespace: stakeholder-api
spec:
  encryptedData:
    db: AgBVR9InSOdl/oQ7nNh3tzcSf6IRlzSGJR+KdrML3mmYqn55mXZb+ni0x4q0eHobcq6OqmDA4xTDS1VokPdo1+vgcM0vU3J3z5N3/L1TQQMQrNfwXE5aZAJFe1Ubpdbbw1EwQWuPt8oWbtimKZ3B8RNKfywJHoAg9FAHepYtCfc/vz6vNOz8f+wH+oCypV/i2Uuf4iyo73xRnu6wCpStucw64M5Ay/QeHBrufPR9KenaoORIGkamBysKN93Bh1RNzGEDjm0ILJa1TCz9fB5QQc+PkahMgfhmZn7tmYK1NW7DCl73oD3z2RaQfC4d4OHG2gbqC9qGEZfwP8iepGI1SeHsdt/sXC4sinhfhBzV+gkE7xYHbyS0T2DBVZWW1P5g80n3ebhj0psbhTlSrr7pgR9tRcb14Z76s/j2AHpbkX5Uidbe/lJ7uUXYvmVtaTXA8njXZVCLKDziQZXwL70xUlgFRhNFEXX1sFNrJ54pR+tc+Mgb7nDRtgtcUL9EkP1FJIm00lnyj6G+JrEF8mMeiRLbDc06Roc3LZqBl7s/Fd7ehrK9IS4FW2OZTe14fEVbUuzYvNeEqnL/N2IgTOEJiCBtHanfhDV76Ln3sGuhufSk8XQ1UDXgV2RufzzEdqaQ4YAzUh99FdUXgwug/MamtH09n/JMshQ/hoo42ECb9FKS2TvnkZgVEfQJOVF4P0aOehKS7am4z3FVC9XSVWlzmKkkOePDYBUw/Ig8qTNTLszrOM3fYlrjD8RZ469Ab0mqqo94zlQa9qEyN907dbMNz9Lt+U8cofM7hCn1rQpq2E8hEDSblN8yc2okm8RzGXPrCOF5Z0QQpRRF6A4Z0IShhmjli3eWuYukL0tXKafY/tDy0/477v5rrxLXMeWpJy6UPR9G97joHi40srRCLBjD80hJNA==
  template:
    metadata:
      creationTimestamp: null
      name: database-migration-connection
      namespace: stakeholder-api

