openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/gwynndp/Stakeholders/1.0.0
info:
  description: Stakeholder microservice API
  version: '1.0.0'
  title: Greenstand Stakeholder API
  contact:
    email: admin@greenstand.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /stakeholders/relations/:id:
    get:
      tags:
        - admins
      summary: gets links to related stakeholders like children and parents
      operationId: getRelations
      description: get all Organization and Person entities that could possibly be linked to the stakeholder as children and parents
      parameters:
        - in: params
          name: id
          description: the id of the currently viewed stakeholder
          required: true
          schema:
            type: uuid or integer
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stakeholder'
        '400':
          description: bad input parameter
    post:
      tags:
        - admins
      summary: adds a new stakeholder relationship
      operationId: createRelation
      description: Adds a stakeholder relation to another stakeholder.
      parameters:
        - in: params
          name: id
          description: the id of the currently viewed stakeholder
          required: true
          schema:
            type: uuid or integer
        - in: query
          name: id
          description: the second stakeholder id, required to create the relation between the stakeholder and to confirm that the relation can be created by the logged in organization
          required: true
          schema:
            type: string
      responses:
        '201':
          description: stakeholder created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stakeholder'
        description: Stakeholder item to add
    delete:
      tags:
        - admins
      summary: removes a relation to a stakeholder
      operationId: deleteStakeholder
      description: Removes a stakeholder's relation to another stakeholder
      parameters:
        - in: params
          name: id
          description: the id of the currently viewed stakeholder
          required: true
          schema:
            type: uuid or integer
      responses:
        '204':
          description: no data, stakeholder deleted
        '400':
          description: 'invalid input, id invalid'
        '304':
          description: error, stakeholder wasn't modified
  /stakeholders/:id:
    get:
      tags:
        - admins
      summary: gets data for one stakeholder including parents and children, id will come from currently viewed stakeholder or from the logged in organization id
      operationId: getStakeholdersById
      description: get all Organization and Person entities that could possibly be linked to the stakeholder as children and parents
      parameters:
        - in: query
          name: search
          description: pass an optional search term for partial match on any part of a name field, phone number, email, etc.
          required: false
          schema:
            type: string
        - in: query
          name: filter
          description: query by field name and value on id, type, name, phone number, email, etc.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stakeholder'
        '400':
          description: bad input parameter
    post:
      tags:
        - admins
      summary: adds a new stakeholder with basic info
      operationId: addStakeholder
      description: Adds a stakeholder to the system
      responses:
        '201':
          description: stakeholder created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stakeholder'
        description: Stakeholder item to add
    patch:
      tags:
        - admins
      summary: updates a stakeholder's info ONLY allowed if the stakeholder is currently related/owned by the logged in organization; allows editing of basic info
      operationId: updateStakeholder
      description: Updates a stakeholder's info
      responses:
        '200':
          description: send back updated stakeholder
        '304':
          description: error, stakeholder wasn't modified
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stakeholder'
        description: Stakeholder item based on the schema with additional keys for children and parents data to link
  /stakeholders:
    get:
      tags:
        - admins
      summary: gets data for all stakeholders, without associated children or parents data
      operationId: getStakeholders
      description: get all Organization and Person entities that could possibly be linked to the stakeholder as children, parents
      parameters:
        - in: query
          name: filter
          description: query by field name and value on id, type, name, phone number, email, search, etc.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stakeholder'
        '422':
          description: bad input parameter
    post:
      tags:
        - admins
      summary: adds a new stakeholder to the admin account with basic info, not including children and parents info
      operationId: addStakeholder
      description: Adds a stakeholder to the system
      responses:
        '201':
          description: stakeholder created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stakeholder'
        description: Stakeholder item to add
    patch:
      tags:
        - admins
      summary: updates a stakeholder's info; allows editing of basic info
      operationId: updateStakeholder
      description: Updates a stakeholder's info
      responses:
        '200':
          description: send back updated stakeholder
        '304':
          description: error, stakeholder wasn't modified
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stakeholder'
        description: Stakeholder item based on the schema with additional keys for children and parents data to link
    delete:
      tags:
        - admins
      summary: removes/disables a stakeholder, un-linking of children and parents
      operationId: deleteStakeholder
      description: Removes/disables a stakeholder & associated info on other tables, like adding children and parents
      parameters:
        - in: query
          name: id
          description: pass an id, required for looking up the org and associated data to delete/disable
          required: true
          schema:
            type: string
      responses:
        '204':
          description: no data, stakeholder deleted
        '400':
          description: 'invalid input, id invalid'
        '304':
          description: error, stakeholder wasn't modified
components:
  schemas:
    Stakeholder:
      type: object
      required:
        - id
        - type
        - org_name
        - first_name
        - last_name
        - email
        - phone
        - website
        - logo_url
        - map
        - children
        - parents
      properties:
        id:
          type: string
          format: uuid
          example: '792a4eee-8e18-4750-a56f-91bdec383aa6'
        type:
          type: string
          format: string
          example: 'O'
        org_name:
          type: string
          format: string
          example: 'Greenstand'
        first_name:
          type: string
          format: string
          example: 'Don'
        last_name:
          type: string
          format: string
          example: 'Juan'
        email:
          type: string
          format: email
          example: 'hello@greenstand.org'
        phone:
          type: string
          format: phone-number
          example: '123-456-7890'
        website:
          type: string
          format: url
          example: 'http://greenstand.org'
        logo_url:
          type: string
          format: url
          example: './logo_192x192.png'
        map:
          type: string
          format: string
          example: '/greenstandMap'
        children:
          type: array
          format: json
          items:
            $ref: '#/components/schemas/Stakeholder'
          example:
            [
              {
                id: '1a05ec87-3c38-4395-b9f3-aa15becedc31',
                type: 'Organization',
                org_name: 'Child One',
                first_name: '',
                last_name: '',
                email: 'child@gmail.com',
                phone: '123-123-1234',
                website: 'childone.com',
                logo_url: './logo_192x192.png',
                map: '/childOne',
              },
              {
                id: '1d2fb06e-e8f7-40de-8e13-ed3eba1abb3a',
                type: 'Organization',
                org_name: 'Child Two',
                first_name: '',
                last_name: '',
                email: 'childtwo@gmail.com',
                phone: '123-234-1234',
                website: 'childtwo.com',
                logo_url: './logo_192x192.png',
                map: '/childTwo',
              },
            ]
        parents:
          type: array
          format: json
          items:
            $ref: '#/components/schemas/Stakeholder'
          example:
            [
              {
                id: '792a4eee-8e18-4750-a56f-91bdec383aa6',
                type: 'Organization',
                org_name: 'Greenstand',
                first_name: '',
                last_name: '',
                email: 'hello@greenstand.com',
                phone: '123-123-2122',
                website: 'greenstand',
                logo_url: './logo_192x192.png',
                map: '/greenstandMap',
              },
            ]
