openapi: 3.1.0
info:
  title: Stakeholders API
  version: '1.0'
servers: []
paths:
  /stakeholder:
    parameters: []
    get:
      summary: Fetches data from the entity table
      tags: []
      operationId: get-stakeholders
      description: 'Get stakeholders based on id,uuid or organization id'
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: integer
            maximum: 100
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: stakeholder_id
        - schema:
            type: integer
          in: query
          name: organization_id
        - schema:
            type: string
            format: uuid
          in: query
          name: stakeholder_uuid
          description: filter by stakeholder_uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    stakeholders:
                      - id: 2
                        type: 'o'
                        name: 'test2'
                        first_name: 'name'
                        last_name: 'name'
                        email: 'emain@email.com'
                        phone: 232323232
                        pwd_reset_required: false
                        website: 'website.com'
                        wallet: 'wallet.com'
                        password: 'password'
                        salt: 'salt'
                        active_contract_id: 1
                        offering_pay_to_plant: false
                        tree_validation_contract_id: 1
                        logo_url: 'logo_url'
                        map: 'map'
                        stakeholder_uuid: '2b601c87-539f-4fa8-831c-92200fa3aab2'
                    totalCount: 1
                    links:
                      prev: 'https://stakeholder.treetracker.org?stakeholder_id=1&offset=0&limit=100'
                      next: 'https://stakeholder.treetracker.org?stakeholder_id=1&offset=200&limit=100'
                properties:
                  stakeholders:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          format: integer
                        type:
                          type: string
                        name:
                          type: string
                        first_name:
                          type: string
                        last_name:
                          type: string
                        email:
                          type: string
                        phone:
                          type: number
                        pwd_reset_required:
                          type: boolean
                        website:
                          type: string
                        wallet:
                          type: string
                        password:
                          type: string
                        salt:
                          type: string
                        active_contract_id:
                          type: number
                          format: integer
                        offering_pay_to_plant:
                          type: boolean
                        tree_validation_contract_id:
                          type: number
                          format: integer
                        logo_url:
                          type: string
                        map:
                          type: string
                        stakeholder_uuid:
                          type: string
                          format: uuid
                  totalCount:
                    type: number
                    format: integer
                  links:
                    type: object
                    required:
                      - prev
                      - next
                    properties:
                      prev:
                        type: string
                        minLength: 1
                        description: Complete link with query string to the previous page of captures
                      next:
                        type: string
                        minLength: 1
                        description: Complete link with query string to the next page of captures
                required:
                  - captures
                  - links
components:
  schemas: {}
